### PR TITLE
Fix related entity title parsing bug

### LINKED ISSUE #350: Related title not parsed
The related title is not parsed. I checked the sanitizePayload function, and it seems that the payload.title for related items is always an empty string "". Therefore, the getDefaultTitle function is never triggered.

 "strapi-plugin-navigation": "^2.2.11"
 "@strapi/strapi": "4.11.0",

### PR DESCRIPTION
**Pull request by ijlind**
## Ticket

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/350

## Summary

Fixes #350. The content type title value was not pulled correctly from the contentTypeEntities-array. The reason was that the comparison against the `related` id failed because one of the values was a string and the other was a number.

## Test Plan

`@strapi/strapi 4.15.0`
`strapi-plugin-navigation 2.2.16`

1. Create or edit a navigation item
2. Make sure that the title field is empty
3. Select a related entity with a valid name field configuration
4. Click the save button
5. The navigation item is saved

### CODE REVIEW

**Review by CodeVoyager — APPROVED** [review]

**Comment by ijlind** [comment]
What is the current process with this project with releases? This fix would be really useful for our project in active development currently. If there are no issues found with this fix, how soon could we expect to see a release with this?

File: admin/src/pages/View/components/NavigationItemForm/index.tsx [hunk 1]
```diff
@@ -221,7 +221,7 @@ const NavigationItemForm: React.FC<NavigationItemFormProps> = ({
       return isString(title) && !isEmpty(title) ? await slugify(title).then(prop("slug")) : undefined;
     } else if (related) {
       const relationTitle = extractRelatedItemLabel({
-        ...contentTypeEntities.find(_ => _.id === related),
+        ...contentTypeEntities.find(_ => String(_.id) === related),
```
Comment (cyp3rius) [inline admin/src/pages/View/components/NavigationItemForm/index.tsx:224]: `_.id.toString() === related.toString()`

to be sure about type of both

**Review by cyp3rius — CHANGES_REQUESTED** [review]

File: admin/src/pages/View/components/NavigationItemForm/index.tsx (hunk 1 above)
Comment (ijlind) [reply admin/src/pages/View/components/NavigationItemForm/index.tsx:224]: Wouldn't it be safer to use `String(...)`? The function parameters of `generateUiRouterKey` defined `related?: string` so it could potentially be undefined. Calling `.toString()` on that would obviously not work.

**Review by cyp3rius — APPROVED** [review]
